### ISSUE TITLE
Value should be a JSON object

### ISSUE THREAD

**Issue by eleaner** [theranger/zabbix-borg#1]
Hi,

Discovery rule is returning "Value should be a JSON object."
I am using borg-enc.conf and zabbix 3.2

could you please help?

**Comment by rootchick** [comment]
I'm experiencing this too on zabbix 4 with borg-enc.conf.  I'm new to zabbix so I'm not sure where to begin to troubleshoot this.

**Comment by lebe-dev** [comment]
1. Original discovery command looks for string "This is a borg repo..." in README files but in current version of borg README string is "This is a Borg Backup.."

2. grep requires `-r` flag and search mask should be `/home/*/README`

Final version for discovery parameter:

```
UserParameter=borg.discover,dirname $(grep -sirlm1 "This is a Borg Backup" /home/*/README) | awk 'BEGIN{printf "{\"data\":["}; {i=split($1,path,"/"); printf c"{\"{#PATH}\":\""$1"\", \"{#HOST}\":\"" path[i-1] "\", \"{#DIR}\":\"" path[i] "\"}";c="," };  END{print "]}"}'
```
